/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import Controller.Conexion;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.ResultSet;
/**
 *
 * @author paulo
 */
public class PublicarNotas extends javax.swing.JInternalFrame {
    
int CursoSelecionado()
{
    int curso=0;
    if(cmbCursos.getSelectedItem().equals("1ro de Secundaria"))
    {
        curso=1;
        return curso;
    }
    else if(cmbCursos.getSelectedItem().equals("2do de Secundaria"))
    {
        curso=2;
        return curso;
    }
     else if(cmbCursos.getSelectedItem().equals("3ro de Secundaria"))
    {
        curso=3;
        return curso;
    }
     else if(cmbCursos.getSelectedItem().equals("4to de Secundaria"))
    {
        curso=4;
        return curso;
    }
     else if(cmbCursos.getSelectedItem().equals("5to de Secundaria"))
    {
        curso=5;
        return curso;
    }
     else if(cmbCursos.getSelectedItem().equals("6to de Secundaria"))
    {
        curso=6;
        return curso;
    }
    return curso;
}    
void mostrarCursosCMB(int id_profe)
{
    Conexion conexion= new Conexion();
    Connection conectado=conexion.Conectar();
    String curso;
    int cursoSelecionado;
    try
    {
        Statement statement=conectado.createStatement();
        ResultSet resultado= statement.executeQuery("SELECT*FROM profe_cursos JOIN Cursos ON  profe_cursos.id_curso= Cursos.id_curso WHERE id_profe='"+id_profe+"'");
        while(resultado.next())
        {
           curso=resultado.getString("curso");
           cmbCursos.addItem(curso);
           
        }
        cursoSelecionado= CursoSelecionado();
        
        ResultSet resultado2=statement.executeQuery("SELECT DISTINCT m.materia\n" +
        "FROM profe_mate p\n" +
        "JOIN Materias m ON p.id_materia = m.id_materia\n" +
        "JOIN curso_mate cm ON m.id_materia = cm.id_materia\n" +
        "JOIN profe_cursos pc ON cm.id_curso = pc.id_curso\n" +
        "JOIN Cursos c ON pc.id_curso = c.id_curso\n" +
        "WHERE p.id_profe = "+id_profe+" AND c.id_curso = "+cursoSelecionado+";");
        
        while(resultado2.next())
        {
          cmbMaterias.addItem(resultado2.getString("materia"));
        }
        
        
    }   
    catch(SQLException ex)
    {
      Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);   
    }
    
    

}


 
    public PublicarNotas() 
    {
        initComponents();
        mostrarCursosCMB(2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbCursos = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbMaterias = new javax.swing.JComboBox<>();

        cmbCursos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        cmbCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCursosActionPerformed(evt);
            }
        });

        jLabel1.setText("Seleccione Materia");

        jLabel2.setText("Seleccione Curso");

        cmbMaterias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", " " }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbCursos, 0, 192, Short.MAX_VALUE)
                            .addComponent(cmbMaterias, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(106, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(149, 149, 149)
                    .addComponent(jLabel2)
                    .addContainerGap(155, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(cmbCursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(185, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(17, 17, 17)
                    .addComponent(jLabel2)
                    .addContainerGap(273, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCursosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCursosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbCursos;
    private javax.swing.JComboBox<String> cmbMaterias;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}


